version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: node build/server/index.js

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    deploy:
      replicas: 3
    command: node build/client/index.js
    depends_on:
      - server