version: "3.8"

services:
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: node build/monitor/index.js
    ports:
      - 3000:3000

  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    deploy:
      replicas: 3
    command: node build/node/index.js