enum SocketEvents {
    MONITOR_HANDSHAKE = 'MONITOR_HANDSHAKE',
    NODE_MONITOR_HANDSHAKE = 'NODE_MONITOR_HANDSHAKE',

    NODE_BROADCAST = 'NODE_BROADCAST',
    NODE_BROADCAST_RESPONSE = 'NODE_BROADCAST_RESPONSE',

    NODE_TABLE_SHARE = 'NODE_TABLE_SHARE',
    NODE_TABLE_SHARE_RESPONSE = 'NODE_TABLE_SHARE_RESPONSE',

    MESSAGE_SHARE = 'MESSAGE_SHARE',
}

export default SocketEvents;
