enum SocketEvents {
    MONITOR_HANDSHAKE = 'MONITOR_HANDSHAKE',
    NODE_MONITOR_HANDSHAKE = 'NODE_MONITOR_HANDSHAKE',

    NODE_BROADCAST = 'NODE_BROADCAST',
    NODE_BROADCAST_RESPONSE = 'NODE_BROADCAST_RESPONSE',
}

export default SocketEvents;
